---
openapi: 3.0.0
info:
  title: 'InPost ShipX'
  description: InPost ShipX API
  version: '1.0'
  contact: { }
tags: [ ]
security:
  - bearer: [ ]
servers:
  - description: Production
    url: https://api-shipx-pl.easypack24.net/v1
  - description: Sandbox
    url: https://sandbox-api-shipx-pl.easypack24.net/v1

paths:
  "/organizations/{organization_id}/shipments":
    parameters:
      - name: organization_id
        required: true
        in: path
        schema:
          type: string
    get:
      tags: [ Shipments ]
      operationId: getShipments
      responses:
        '200':
          description: ''
          content:
            'application/json':
              schema: { }
    post:
      tags: [ Shipments ]
      operationId: createShipment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateShipment"
      responses:
        '201':
          description: ''
          content:
            'application/json':
              schema: { }
  /shipments/{id}:
    parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
    delete:
      tags: [ Shipments ]
      operationId: cancelShipment
      responses:
        '204':
          description: ''
  /statuses:
    get:
      tags: [ Statuses ]
      operationId: listStatuses
      responses:
        '200':
          description: ''
          content:
            'application/json':
              schema:
                type: object
                properties:
                  name:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
components:
  securitySchemes:
    bearer:
      scheme: bearer
      type: http
  schemas:
    CreateShipment:
      type: object
      required:
        - receiver
        - parcels
        - service
        - custom_attributes
      properties:
        receiver:
          $ref: '#/components/schemas/Receiver'
        parcels:
          type: array
          items:
            $ref: '#/components/schemas/ParcelSimple'
        custom_attributes:
          type: object
          required:
            - target_point
          properties:
            target_point:
              type: string
              description: Kod paczkomatu
        insurance:
          $ref: '#/components/schemas/MoneyData'
        cod:
          $ref: '#/components/schemas/MoneyData'
        service:
          type: string
          enum:
            - inpost_locker_standard
        additional_services:
          type: array
          items:
            type: string
            enum:
              - sms
              - email
              - saturday
              - cod
        reference:
          type: string
          maxLength: 100
        comments:
          type: string
        external_customer_id:
          type: string
        mpk:
          type: string
    Receiver:
      type: object
      required:
        - phone
        - email
      properties:
        name:
          type: string
        company_name:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: object
          properties:
            street:
              type: string
            building_number:
              type: string
            city:
              type: string
            post_code:
              type: string
            country_code:
              type: string

    MoneyData:
      type: object
      properties:
        amount:
          type: string
        currency:
          type: string
    ParcelSimple:
      type: object
      properties:
        id:
          type: string
        template:
          type: string
          enum:
            - small
            - medium
            - large
        dimensions:
          type: object
          properties:
            length:
              type: string
            width:
              type: string
            height:
              type: string
            unit:
              type: string
              enum:
                - mm
        weight:
          type: object
          properties:
            amount:
              type: string
            unit:
              type: string
              enum:
                - kg